src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields="emailCanonical", errorPath="email", message="fos_user.email.already_used")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\Column(name="first_name", type="string", length=100)
     *
     * @Assert\Length(min=1, max=100)
     * @Assert\NotBlank()
     */
    protected $firstName;

    /**
     * @ORM\Column(name="last_name", type="string", length=100)
     *
     * @Assert\Length(min=1, max=100)
     * @Assert\NotBlank()
     */
    protected $lastName;

    /**
     * User constructor.
     */
    public function __construct()
    {
        parent::__construct();

        $this->roles = ['ROLE_USER'];
    }

    public function setEmail($email)
    {
        parent::setEmail($email);

        // username is identical to the Email
        parent::setUsername($email);
    }

    /**
     * @param string $username
     */
    public function setUsername($username): void
    {
        $this->username = $this->email;
    }

    /**
     * @return mixed
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * @param mixed $firstName
     */
    public function setFirstName($firstName): void
    {
        $this->firstName = $firstName;
    }

    /**
     * @return mixed
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    public function isAdmin(): bool
    {
        return $this->hasRole('ROLE_ADMIN');
    }

    /**
     * @param mixed $lastName
     */
    public function setLastName($lastName): void
    {
        $this->lastName = $lastName;
    }

    public function getFullname()
    {
        return "{$this->getFirstName()} {$this->getLastName()}";
    }

    public function isAccountNonLocked()
    {
        return $this->enabled;
    }
}

templates/bundles/FOSUserBundle/Profile/edit_content.html.twig
{% trans_default_domain 'FOSUserBundle' %}
{% form_theme form with 'bootstrap_4_layout.html.twig' %}

<div class="row">
    <div class="col-lg-6 offset-lg-3">
        {{ form_start(form, { 'action': path('fos_user_profile_edit'), 'attr': { 'class': 'fos_user_profile_edit' } }) }}

        <div class="form-group">
            {{ form_row(form.email) }}
        </div>

        <div class="form-group">
            {{ form_row(form.firstname) }}
        </div>

        <div class="form-group">
            {{ form_row(form.lastname) }}
        </div>

        {{ form_rest(form)}}

        <div>
            <input class="btn btn-primary" type="submit" value="{{ 'profile.edit.submit'|trans }}"/>
        </div>
        {{ form_end(form) }}
    </div>
</div>

templates/bundles/FOSUserBundle/Profile/show_content.html.twig
{% trans_default_domain 'FOSUserBundle' %}

<div class="row">
    <div class="col-lg-6 offset-lg-3">
        <div class="fos_user_user_show">
            <h4>User Profile</h4>
            <p>
                <b>Name:</b> {{ user.firstname }} {{ user.lastname }}
            </p>
            <p>
                <b>Email:</b> {{ user.email }}
            </p>
            <p>
                <b>Role:</b> {{ user.admin ? 'Admin' : 'User' }}
            </p>
            <p>
                <a class="btn btn-info" href="{{ url('fos_user_profile_edit') }}">Edit</a>
            </p>
        </div>
    </div>
</div>